#ifndef UNIFORM_BUFFER_OBJECT
#define UNIFORM_BUFFER_OBJECT UniformBufferObject
#endif 

#ifndef VERTEX_POSITION_LOCATION
#define VERTEX_POSITION_LOCATION 0
#endif

#ifndef VERTEX_COLOR_LOCATION
#define VERTEX_COLOR_LOCATION 1
#endif

#ifndef UNIFORM_BLOCK_BINDING
#define UNIFORM_BLOCK_BINDING 0
#endif